# docker-compose is for testing a single application where all the resources (LoadBalancer, PersistentVolumes, ClusterIP Services) live ona single machine (host), single network 
# docker-compose can use images created by dockerfiles if they are in the dockerhub repository or github repository
version: "3"
services:
    redis:
        image: redis:6.2.7
        ports:
            - "6379"
        volumes:
            # The redis.conf on the local machine. The context is the location of the current file
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            # Maps the local machine persistent volume to the directory on the container
            # Will store the dump.rdb file specified in the redis.conf
            -  ./data:/data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"] 